blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('blog/<int:pk>', views.BlogDetail.as_view(), name='blogview'),
    path('add_blogpost/', views.CreateBlog.as_view(), name='add_blogpost'),
    path('add_topic/', views.CreateTopic.as_view(), name='add_topic'),
    path('blogpost/edit/<int:pk>', views.EditBlog.as_view(), name='edit_blogpost'),
    path('blogpost/<int:pk>/delete', views.DeleteBlog.as_view(), name='delete_blogpost'),
    path('topic/<str:item>/', views.topicview, name='topic'),
    path('search/', views.search, name='search'),
    path('search/<int:pk>', views.BlogDetail.as_view(), name='blogpost'),
    path('like/<int:pk>', views.likes, name='like'),
]

ptu_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user_profiles/', include('django.contrib.auth.urls')),
    path('user_profiles/', include('user_profile.urls'))
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from datetime import datetime, date
from PIL import Image



User = get_user_model()


class Topic(models.Model):
    name = models.CharField(_("title"), max_length = 255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')



class BlogPost(models.Model):
    title = models.CharField(_("title"), max_length = 255)
    title_tag = models.CharField(_("title tag"), max_length = 255, default='Fox blog')
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name="blog_posts")
    body = RichTextField(_("body"), blank = True, null = True)
    creation_date = models.DateField(_("created"), auto_now_add=True)
    topic = models.ForeignKey(Topic, verbose_name=_("topic"), related_name='blogpost_topics', on_delete=models.CASCADE)
    image = models.ImageField(_("image"), null = True, blank = True, upload_to='images/', default = 'images/default.png')
    users_readlater = models.ManyToManyField(User, related_name="user_readlater", blank=True)
    likes = models.IntegerField(_("likes"), default = 0)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            image = Image.open(self.image.path)
            if image.width > 300 or image.height > 300:
                output_size = (300, 300)
                image.thumbnail(output_size)
                image.save(self.image.path)


    def get_absolute_url(self):
        return reverse("blogview")


    def __str__(self):
        return f"{self.title} : {self.author}"

    def get_absolute_url(self):
        return reverse('home')
        
    
class BlogComment(models.Model):
    blogpost = models.ForeignKey(BlogPost, related_name = 'comments', on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    created_at = models.DateField(_("created at"), auto_now_add = True)
    content = models.TextField(_("content"), max_length=2000)



    def __str__(self):
        return self.user.username


class BlogLike(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "user_likes")
    liked_blog = models.ForeignKey(BlogPost, on_delete = models.CASCADE, related_name = 'blogpost_likes')

    def __str__(self):
        return f"{self.user.username} likes {self.liked_blog.title}"

blog/forms.py
from django import forms
from . import models
from django.utils.timezone import datetime, timedelta
from django.utils.translation import gettext_lazy as _



class BlogPostForm(forms.ModelForm):
    class Meta:
        model = models.BlogPost
        fields = ('title', 'title_tag', 'author', 'topic', 'body', 'image')

        widgets = {
            'title' : forms.TextInput(attrs = {'class':'form-control', 'placeholder': 'Title'}),
            'title_tag' : forms.TextInput(attrs = {'class':'form-control'}),
            'author' : forms.TextInput(attrs = {'class':'form-control', 'value' : '', 'id':'author', 'type':'hidden'}),
            'topic' : forms.Select(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs = {'class':'form-control', 'placeholder': 'Write your story here'}),
            'image' : forms.FileInput(attrs = {'class': 'form-control'})
        }


class EditBlogPostForm(forms.ModelForm):
    class Meta:
        model = models.BlogPost
        fields = ('title','title_tag', 'topic',  'body', 'image')

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Title'}),
            'title_tag' : forms.TextInput(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control', 'placeholder': 'Write your story here'}),
            'topic' : forms.Select(attrs={'class':'form-control'}),
        }
        

class CommentForm(forms.ModelForm):
    def is_valid(self) -> bool:
        valid = super().is_valid()
        if valid:
            user = self.cleaned_data.get("user")
            recent_posts = models.BlogComment.objects.filter(
                user=user,
                created_at__gte=(datetime.utcnow()-timedelta(hours=1))
            ) 
            if recent_posts:
                return False
        return valid

    class Meta:
        model = models.BlogComment
        fields = ('content', 'blogpost', 'user', )
        widgets = {
            'content' : forms.Textarea(attrs = {'class':'form-control', 'placeholder': 'Comment the blog post'}),
            'blogpost': forms.TextInput(attrs = {'class':'form-control', 'value' : '', 'id':'blogpost', 'type':'hidden'}),
            'user': forms.TextInput(attrs = {'class':'form-control', 'value' : '', 'id':'user', 'type':'hidden'}),
        }

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from .models import BlogPost, Topic, BlogLike
from django.shortcuts import render, get_object_or_404
from .forms import BlogPostForm, EditBlogPostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _


class Home(ListView):
    model = BlogPost
    paginate_by = 3
    template_name = 'home.html'
    ordering = ['-creation_date']


    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(Home, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context


class BlogDetail(FormMixin, DetailView):
    model = BlogPost
    template_name = 'blog_details.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blogview', kwargs={'pk': self.get_object().id})

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            messages.error(self.request, _("Your comment was posted."), extra_tags='comment')
            return self.form_valid(form)
        else:
            messages.error(self.request, _("Malaka, you're posting too much!"), extra_tags='comment')
            return self.form_invalid(form)


    def form_valid(self, form):
        form.instance.blogpost = self.get_object()
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


    def get_initial(self):
        return {
            'blogpost' : self.get_object(),
            'user' : self.request.user
        }


    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(BlogDetail, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context




class CreateBlog(LoginRequiredMixin, CreateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'add_blogpost.html'

    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(CreateBlog, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context


class EditBlog(LoginRequiredMixin, UpdateView):
    model = BlogPost
    form_class = EditBlogPostForm
    template_name = 'edit_blog.html'

    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(EditBlog, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context


class DeleteBlog(LoginRequiredMixin, DeleteView):
    model = BlogPost
    template_name = 'delete_blog.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(DeleteBlog, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context

    

class CreateTopic(LoginRequiredMixin, CreateView):
    model = Topic
    template_name = 'add_topic.html'
    fields = '__all__'

    def get_context_data(self, *args, **kwargs):
        item_menu = Topic.objects.all()
        context = super(CreateTopic, self).get_context_data(*args, **kwargs)
        context['item_menu'] = item_menu
        return context


def topicview(request, item):
    topic = get_object_or_404(Topic, name = item)
    paginate = Paginator(BlogPost.objects.filter(topic = topic), 2)
    page = request.GET.get('page')
    topic_blogposts = paginate.get_page(page)
    nums = "a" * topic_blogposts.paginator.num_pages
    return render(request, 'topics.html', {'topic' : topic, 'topic_blogposts' : topic_blogposts, 'nums' : nums})



def search(request):
    query = request.GET.get('query')
    search_results = BlogPost.objects.filter(Q(title__icontains=query) | 
        Q(author__username__icontains=query) | 
        Q(topic__name__icontains=query) 
    )
    page = request.GET.get('page')
    paginator = Paginator(search_results, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    nums = "a" * posts.paginator.num_pages
    return render(request, 'search.html', {'blogposts': search_results, 'query': query, 'blogposts' : posts, 'nums' : nums})

@login_required
def likes(request, pk):
    user = request.user
    blogpost = BlogPost.objects.get(id = pk)
    current_likes = blogpost.likes
    liked = BlogLike.objects.filter(user = user, liked_blog = blogpost).count()
    if not liked:
        liked = BlogLike.objects.create(user = user, liked_blog = blogpost)
        current_likes += 1
        messages.success(request, _("You liked this blog post."))
    else:
        liked = BlogLike.objects.filter(user = user, liked_blog = blogpost).delete()
        current_likes -= 1
        messages.success(request, _("You unliked this blog post."))
    blogpost.likes = current_likes
    blogpost.save()
    return HttpResponseRedirect(reverse('blogview', args = [pk]))

blog/templates/add_blogpost.html
{% extends 'base.html' %}
{% block title %}Create new blog post{% endblock title %}
{% block content %}


<style>
    .django-ckeditor-widget div {
        width: 1110px;
    }
</style>


{% if user.is_authenticated %}
    <h1>Add blog posts</h1>
    <br/><br/>
    <div class="form-group">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class='text-center'>  
                <button class="btn btn-success btn-lg btn-block">Post</button>
            </div>
        </form>
    </div>
{% else %}
The page is only for registered users.
{% endif %}


<script>
    var name = "{{ user.id }}";
    document.getElementById('author').value 
        = name;
</script>
{% endblock content %}

blog/templates/add_topic.html
{% extends 'base.html' %}
{% block title %}Create new topic for blogs {% endblock title %}
{% block content %}

{% if user.is_authenticated %}
    <h1>Add topic</h1>
    <br/><br/>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success mt-5">Create Topic</button>
        </form>
    </div>
{% else %}
The page is only for registered users.
{% endif %}

{% endblock content %}

blog/templates/delete_blog.html
{% extends 'base.html' %}
{% block title %}Delete blogpost{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.id == blogpost.author.id %}
        <h1 class="mt-3">Delete blog posts</h1>
        <br/><br/>
        <h3>Delete: {{ blogpost.title }}</h3>
        <br/>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                <strong>If you delete blog it will be gone forever</strong><br/><br/>
                <button class="btn btn-danger">Delete</button>
            </form>
        </div>
    {% else %}
        <div class="container">
            <h1 class="mt-2">Only blogs creator can delete his blog.</h1>
        </div>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/>
    {% endif %}
{% else %}
The page is only for registered users.
{% endif %}
<br/><br/><br/><br/><br/>
{% endblock content %}

blog/templates/edit_blog.html
{% extends 'base.html' %}
{% block title %}Edit blogpost{% endblock title %}
{% block content %}


<style>
    .django-ckeditor-widget div {
        width: 1110px;
    }
</style>


{% if user.is_authenticated %}
    {% if user.id == blogpost.author.id %}
        <h1>Edit blog posts</h1>
        <br/><br/>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-success">Post</button>
            </form>
        </div>
    {% else %}
    Blog can be edited by it's creator.
    {% endif %}
{% else %}
The page is only for registered users.
{% endif %}

{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<!-- karuselės pradžia-->

<style>
    .album img {    
        padding: 5px; 
        width: 290px;
        height: 260px;
    }
</style>

<main>
    <section class="py-5 text-center container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="first-slide" src="https://d18lkz4dllo6v2.cloudfront.net/cumulus_uploads/entry/43959/adobe-aliens.jpeg?pw=1200" width="1200" height="350" alt="First slide">
                <div class="container">
                <div class="carousel-caption text-left">
                    <h1>{% trans "Do aliens exist?" %}</h1>
                </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="second-slide" src="https://miro.medium.com/max/1400/1*GvnuAR0VEjyFU2jRuCjIJw.png" width="1200" height="350" alt="Second slide">
                <div class="container">
                <div class="carousel-caption text-left">
                    <h2> {% trans "Everything is Connected" %} </h2>
                </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="third-slide" src="https://i.guim.co.uk/img/media/c360c56c9be61ab2a2b56ba4eac6b1810445fdb6/0_0_3000_1800/master/3000.jpg?width=1200&quality=85&auto=format&fit=max&s=b0f4bb256436685cded8e936cc429e41" 
                    width="1200" height="350" alt="Third slide">
                <div class="container">
                <div class="carousel-caption text-right">
                    <p>{% trans "my favourite conspiracy theory is that everything will eventually turn out okay" %}</p>
                </div>
                </div>
            </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans "Previous" %}</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans "Next" %}</span>
            </a>
        </div>
    </section>
    <hr>



<!-- karuselės pabaiga-->

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">{% trans "Enjoy reading, writing, posting, creating" %}</div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                    {% for blogpost in blogpost_list %}
                    <div class="col">
                        <div class="card" style="max-width: 22rem;">
                        <div class="shadow-lg p-3 mb-0 bg-white rounded">
                                <div class="d-flex justify-content-center">
                                    <img class="img-fluid" src="{{ blogpost.image.url }}" alt="Responsive image">
                                </div>
                            <div class="card-body">
                                <p class="card-text text-center">
                                    <a href="{% url 'blogview' blogpost.pk %}">{{ blogpost.title }}</a>
                                    {% trans "by:" %}
                                    {% if user.id == blogpost.author.id %}
                                        <a href="{% url 'mydashboard' %}"><small>@{{ blogpost.author }}</small></a>
                                    {% else %}
                                        <a href="{% url 'otherprofile' blogpost.author.profile.id %}"><small>@{{ blogpost.author }}</small></a>
                                    {% endif %}
                                </p>
                                <div class="card-text text-center">
                                    <p class="card-text">{{ blogpost.body|slice:":50"|safe }}</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <div class="btn-group">
                                        {% if user.is_authenticated %}
                                            {% if user.id == blogpost.author.id %}
                                                <a href="{% url 'edit_blogpost' blogpost.pk %}">
                                                    <button type="button" class="btn btn-sm btn-outline-secondary mr-5">{% trans "Edit" %}</button>
                                                </a>
                                                <a href="{% url 'delete_blogpost' blogpost.pk %}">
                                                    <button type="button" class="btn btn-sm btn-outline-secondary">{% trans "Delete" %}</button>
                                                </a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                                <small class="text-muted">{{ blogpost.creation_date|timesince }}</small>
                            </div>
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <br/>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo {% trans "First" %}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a></li> 
        {% endif %}
            <li class="page-item disabled"><span class="page-link">{{ page_obj.number}} {% trans "out of" %} {{ page_obj.paginator.num_pages }}</span></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last" %} &raquo</a></li>
        {% endif %}
       </ul>
    </nav>
</main>
{% endblock content %}

blog/templates/search.html
{% extends 'base.html' %}
{% block title %}Search results {{ query }}{% endblock title %}
{% block content %}


<style>
  .blog-img img {
      width: 320px;
      height: 198px;
  }

</style>

<h1 class="mt-2">Search according to {{query}} results: </h1>
  </br>

{% if blogposts %}
  <div class="album py-5 bg-light">
    <div class="container">
        {% for blogpost in blogposts %}
            <div class="card mb-3" style="max-width: 1040px; max-height: 200px;">
                <div class="row no-gutters">
                <div class="col-md-4">
                    <div class="blog-img">
                        <img src="{{ blogpost.image.url }}" class="card-img" alt="...">
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                    <a href="{% url 'blogview' blogpost.pk %}"><h5 class="card-title">{{ blogpost.title }}</a>
                      <div class="post-author">
                        By:
                        <small>
                        {% if user.id == blogpost.author.id %}
                            <a href="{% url 'mydashboard' %}">
                                @{{ blogpost.author }}
                            </a>
                        {% else %}
                            <a href="{% url 'otherprofile' blogpost.author.profile.id %}">
                                @{{ blogpost.author }}
                            </a>
                        {% endif %}
                        </small>
                    </div>
                    <p class="card-text">{{ blogpost.body|slice:":150"|safe }}...</p>
                    </div>
                </div>
                </div>
            </div>
         {% endfor %}
    </div>
</div>
</hr>
<br/>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center"> 
    {% if blogposts.has_previous %}
      <li class="page-item"><a class="page-link" href="?query={{query}}&page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?query={{query}}&page={{ blogposts.previous_page_number }}">Previous</a></li>
    {% endif %} 
    {% for i in nums %}
      <li class="page-item"><a class="page-link" href="?query={{query}}&page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
    {% endfor %}
    {% if blogposts.has_next %}
    <li class="page-item"><a class="page-link" href="?query={{query}}&page={{ blogposts.next_page_number }}">Next</a></li>
    <li class="page-item"><a class="page-link" href="?query={{query}}&page={{ blogposts.paginator.num_pages }}">Last &raquo</a></li>
    {% endif %}
   </ul>
  </nav>
{% else %}
    <p>We couldn't find anything</p>
{% endif %}

{% endblock content %}

blog/templates/topics.html
{% extends 'base.html' %}
{% block content %}
{% block title %}{{topic.name}}{% endblock title %}
<style>
    .blog-img img {
        width: 320px;
        height: 198px;
    }
  
</style>
{% if topic_blogposts %}
    <div class="album py-5 bg-light">
        <div class="container">
            {% for blogpost in topic_blogposts %}
                <div class="card mb-3" style="max-width: 1040px; max-height: 200px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                        <div class="blog-img">
                            <img src="{{ blogpost.image.url }}" class="card-img" alt="...">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <a href="{% url 'blogview' blogpost.pk %}"><h5 class="card-title">{{ blogpost.title }}</a>
                            <div class="post-author">
                            By:
                            <small>
                            {% if user.id == blogpost.author.id %}
                                <a href="{% url 'mydashboard' %}">
                                    @{{ blogpost.author }}
                                </a>
                            {% else %}
                                <a href="{% url 'otherprofile' blogpost.author.profile.id %}">
                                    @{{ blogpost.author }}
                                </a>
                            {% endif %}
                            </small>
                            </div>
                            <p class="card-text">{{ blogpost.body|slice:":150"|safe }}...</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <br/>
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center"> 
    {% if topic_blogposts.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ topic_blogposts.previous_page_number }}">Previous</a></li>
    {% endif %} 
    {% for i in nums %}
        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
    {% endfor %}
    {% if topic_blogposts.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ topic_blogposts.next_page_number }}">Next</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ topic_blogposts.paginator.num_pages }}">Last &raquo</a></li>
    {% endif %}
    </ul>
    </nav>
{% else %}
    <div class="container mt-5">
        <h1 class="mt-3">No blogs written on this topic</h1>
    </div>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
{% endif %}
{% endblock content %}